### ISSUE TITLE
Generate Link number figures

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_straight_lines#2]
- [x] distribution of the values of p
- [x] predictive accuracy of all four models

**Comment by aammd** [comment]
@FrancisBanville will continue the _perfectionment_ of the Link figures. We need a figure showing (I suggest) 

- [x] posterior predictions for LSSL, CC, PowerLaw and our BB model, for Species richnesses between 2 and 750 species. 
- [x] Professional and publication-ready colours, clear axis labels and good formatting
- [x] minimum S-1 and maximum S^2 lines
- [x] all 4 figures arranged side-by-side

Question: are 4 panels too many?
