### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/ms_straight_lines#6]
This is a screenshot from the predicted links under different points in the posteriors, and it seems to be weird as the first 3000 and the last 3000 give different results - @aammd what's up?

![Screenshot from 2020-01-14 21-24-27](https://user-images.githubusercontent.com/579329/72399471-4f728400-3714-11ea-969f-bedb017a4971.png)

**Comment by tpoisot** [comment]
Specifically the last 3000 are _a lot more_ noisy (this is from the beta binomial posterior) - are these two models runs that ended up in the same file?

**Comment by tpoisot** [comment]
`heatmap(L_predict)` in #7

**Comment by aammd** [comment]
I have apparently (how?!) appended one run of the model to another 😅 
now resolved, closing this
